# 遅延実行されるプラグイン

[[plugins]] # TOMLのシンタックスハイライト
repo  = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]] # その場で実行できる
repo = 'thinca/vim-quickrun'

[[plugins]] # Markdownの編集をサポート
repo = 'plasticboy/vim-markdown'
on_ft = ['md','mdwn','mkd','mkdn','mark']

# [[plugins]] # c/c++/objcのformat
# repo = 'rhysd/vim-clang-format'
# on_ft = ['c', 'cpp', 'objc']
# hook_add = '''
#   let g:clang_format#auto_format = 1
#   let g:clang_format#style_options = {
#   \ "AlignConsecutiveAssignments":"true",
#   \ "IndentCaseLabels": "true",
#   \ "IndentWidth":4,
#   \ "KeepEmptyLinesAtTheStartOfBlocks":"true",
#   \ "SpacesBeforeTrailingComments":1,
#   \ "TabWidth":4,
#   \ "UseTab":"ForIndentation"}
# '''

# # 自動補完-------------------------------------------
# [[plugins]]
# repo = 'roxma/nvim-yarp'
# if = '''!has('nvim')'''
#
# [[plugins]]
# repo = 'roxma/vim-hug-neovim-rpc'
# if = '''!has('nvim')'''
#
# [[plugins]] # 自動補完(要Python3)
# repo = 'Shougo/deoplete.nvim'
# on_event = 'InsertCharPre'
# hook_source = '''
#   let g:deoplete#enable_at_startup = 1
#   let g:deoplete#auto_complete_delay = 0
#   let g:deoplete#auto_complete_start_length = 1
#   let g:deoplete#enable_camel_case = 0
#   let g:deoplete#enable_ignore_case = 0
#   let g:deoplete#enable_refresh_always = 0
#   let g:deoplete#enable_smart_case = 1
#   let g:deoplete#file#enable_buffer_path = 1
#   let g:deoplete#max_list = 10000
# '''
#
# [[plugins]]
# repo = 'Shougo/neco-vim'
# on_source = ['deoplete']
#
# [[plugins]] # 各filetypeのsyntaxファイルの中にある記述を見て補完候補を追加
# repo = 'Shougo/neco-syntax'
# on_source = ['deoplete']
#
# [[plugins]]
# repo = 'zchee/deoplete-clang'
# on_ft = ['c', 'cpp', 'cmake']
# hook_source = '''
# let g:deoplete#sources#clang#libclang_path = 'C:\Cygwin\lib\clang\5.0.1\lib\windows\libclang_rt.builtins-x86_64.a'
# let g:deoplete#sources#clang#clang_header = 'C:\Cygwin\usr\include'
# '''
# depends = ['deoplete.nvim']


#[[plugins]]
#repo = ''

#[[plugins]]
#repo = ''

#[[plugins]]
#repo = ''

