# プラグインの管理
[[plugins]] # これ使うのに必要
repo = 'Shougo/dein.vim'

[[plugins]] # 非同期実行(vim-clang-formatに必要)
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]] # コメントアウトに便利
repo = 'scrooloose/nerdcommenter'
hook_add ='''
    let g:NERDSpaceDelims = 1
    let g:NERDDefaultAlign='left'
    let g:NERDCreateDefaultMappings = 0
    nmap <Leader>c<Space> <Plug>NERDCommenterToggle
    vmap <Leader>c<Space> <Plug>NERDCommenterToggle
    nmap <Leader>cA <Plug>NERDCommenterAppend
    " TODOコメント追加
    nmap <Leader>ctd <Plug>NERDCommenterAppendTODO:<Space>
    " TODOをlocation listとして開く
	nnoremap <Leader>tl :vimgrep /TODO:/j %<CR>:cwindow<CR>
	" TODO: 他のアノテーションも追加
'''

# ----Markdownサポート----
[[plugins]] # Markdownの編集をサポート
repo = 'plasticboy/vim-markdown'
on_ft = 'md'
hook_add = '''
	let g:vim_markdown_folding_disabled=1
	let g:vim_markdown_new_list_item_indent = 0
'''

[[plugins]] # テーブルの生成を補助?
repo = 'godlygeek/tabular'
on_ft = 'md'

[[plugins]] # テーブルの生成
repo = 'dhruvasagar/vim-table-mode'
on_ft = 'md'
hook_add = '''
	let g:table_mode_corner='|'
	let g:table_mode_tableize_map = '<Leader>tb'
'''

[[plugins]] # markdown用のctags
repo = 'jszakmeister/markdown2ctags'
on_ft = 'md'

[[plugins]] # tagジャンプ
repo = 'majutsushi/tagbar'
depends = ['markdown2ctags']
hook_add = '''
	let g:tagbar_autofocus = 1
	let g:tagbar_width = 30
	nnoremap <silent> <leader>tt :TagbarToggle<CR>
	let g:tagbar_type_markdown = {
		\ 'ctagstype': 'markdown',
		\ 'ctagsbin' : $HOME . '/.vim/dein/repos/github.com/jszakmeister/markdown2ctags/markdown2ctags.py',
		\ 'ctagsargs' : '-f - --sort=yes',
		\ 'kinds' : [
		\ 's:sections',
		\ 'i:images'
		\ ],
		\ 'sro' : '|',
		\ 'kind2scope' : {
		\ 's' : 'section',
		\ },
		\ 'sort': 0,
		\ }
'''

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]] # ステータスラインとバッファ表示の強化
repo = 'vim-airline/vim-airline'
hook_add = '''
	" ステータスラインの表示内容強化
	set laststatus=2 " ステータスラインを常に表示
	set noshowmode   " 現在のモードを日本語表示しない
	set showcmd      " 打ったコマンドをステータスラインの下に表示
	set ruler        " ステータスラインの右側にカーソルの現在位置を表示する
	" カーソルキーでbuffer移動
	nnoremap <C-p> :bp<CR>
	nnoremap <C-n> :bn<CR>
	let g:airline_theme = 'powerlineish'
	let g:airline_powerline_fonts = 1
	let g:airline#extensions#tagbar#enabled = 1
	let g:airline#extensions#branch#enabled = 1
	let g:airline#extensions#tabline#enabled = 1
	let g:airline#extensions#wordcount#enabled = 0
	let g:airline#extensions#tabline#formatter = 'unique_tail'
	let g:airline#extensions#ale#error_symbol = ' '
	let g:airline#extensions#ale#warning_symbol = ' '
	let g:airline#extensions#default#layout = [
    \ [ 'a', 'b', 'c' ],
    \ [ 'x', 'y', 'z', 'warning' , 'error']]
    let g:airline#extensions#default#section_truncate_width = {
    \ 'b': 79,
    \ 'x': 60,
    \ 'y': 100,
    \ 'z': 45,
    \ 'warning': 80,
    \ 'error': 80,
    \ }
	let g:airline_section_z = '%3v:%l/%L %3p%%'
'''
depends = ['vim-airline-themes','tagbar']

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]] # 構文チェック
repo = 'w0rp/ale'
hook_add ='''
	let g:ale_echo_msg_error_str = nr2char(0xf421)
	let g:ale_echo_msg_warning_str = nr2char(0xf420)
	let g:ale_echo_msg_info_str = nr2char(0xf05a)
	let g:ale_sign_error = g:ale_echo_msg_error_str
	let g:ale_sign_warning = g:ale_echo_msg_warning_str
	let g:ale_statusline_format = [
	\ g:ale_echo_msg_error_str . ' %d',
	\ g:ale_echo_msg_warning_str . ' %d',
	\ nr2char(0xf4a1) . '  ']
	let g:ale_fix_on_save = 1
	let g:ale_sign_column_always = 1
	let g:ale_lint_on_text_changed = 0
	let g:ale_lint_on_insert_leave = 1
	let b:ale_linters = {
	\	'c':['clang'],
	\	'cpp':['clang'],
	\	'python': ['flake8'],
	\	'vim': ['vint'],
	\}
	let g:ale_fixers = {
	\   'c': ['clang-format'],
	\   'cpp': ['clang-format'],
	\   'python': ['black','isort'],
	\}
	let g:ale_c_clangformat = '-style="{
	\   AlignConsecutiveAssignments:true,
	\   AlignConsecutiveDeclarations:true,
	\   IndentCaseLabels":true,
	\   IndentWidth:4,
	\   KeepEmptyLinesAtTheStartOfBlocks:true,
	\   SpacesBeforeTrailingComments:1,
	\   TabWidth":4,
	\   UseTab:ForIndentation	
	\}"'
	let g:ale_cpp_clangformat = '-style="{
	\   AlignConsecutiveAssignments:true,
	\   AlignConsecutiveDeclarations:true,
	\   IndentCaseLabels":true,
	\   IndentWidth:4,
	\   KeepEmptyLinesAtTheStartOfBlocks:true,
	\   SpacesBeforeTrailingComments:1,
	\   TabWidth":4,
	\   UseTab:ForIndentation	
	\}"'
	autocmd vimrc FileType help,qf,man,ref let b:ale_enabled = 0
'''

# [[plugins]] # gitをvimで操作
# repo = 'tpope/vim-fugitive'

[[plugins]] # カラースキーム
repo = 'morhetz/gruvbox'
hook_add = '''
	set background=dark
	autocmd vimrc VimEnter * nested colorscheme gruvbox
'''

[[plugins]] # 括弧関連便利になる
repo = 'tpope/vim-surround'

[[plugins]] # 括弧などを入力したときの挙動をスマートに補完
repo = 'jiangmiao/auto-pairs'

[[plugins]] # マーク位置の表示
repo = 'kshenoy/vim-signature'

[[plugins]] # インデントの深さを可視化(要tabstop&shiftwidth設定)
repo = 'nathanaelkane/vim-indent-guides'
hook_add = '''
	let g:indent_guides_enable_on_vim_startup = 1
	let g:indent_guides_auto_colors = 0
	autocmd VimEnter,Colorscheme * :hi IndentGuidesOdd  ctermbg=darkgrey
	autocmd VimEnter,Colorscheme * :hi IndentGuidesEven ctermbg=lightgrey
'''

[[plugins]] # 適切なカーソルラインのハイライト
repo = 'delphinus/vim-auto-cursorline'

[[plugins]] # nvim系に必要
repo = 'roxma/nvim-yarp'
if = "!has('nvim')"

[[plugins]] # nvim系に必要
repo = 'roxma/vim-hug-neovim-rpc'
if = "!has('nvim')"

[[plugins]] # スニペット定義ファイル
repo = 'Shougo/neosnippet-snippets'

# ----lsp補完----
[[plugins]]
repo = 'autozimu/LanguageClient-neovim'
rev = 'next'
build = 'bash install.sh'
# on_event = 'VimEnter'
hook_add = '''
	let g:LanguageClient_serverCommands = {
		\ 'c': ['clangd-6.0'],
		\ 'cpp': ['clangd-6.0'],
		\ 'objc': ['clangd-6.0'],
		\ 'objcpp': ['clangd-6.0'],
		\ 'python': ['pyls'],
		\ }
	let g:LanguageClient_autoStart = 1
	let g:LanguageClient_diagnosticsEnable = 0
	let g:LanguageClient_hasSnippetSupport = 0
	set omnifunc=LanguageClient#complete
	let g:deoplete#enable_at_startup = 1
	let g:deoplete#file#enable_buffer_path = 1
	nnoremap <Leader>ld :call LanguageClient_textDocument_definition()<CR>
	nnoremap <Leader>lr :call LanguageClient_textDocument_rename()<CR>
'''
# [[plugins]] # LSP補完
# repo = 'neoclide/coc.nvim'
# build = 'coc#util#install()'

[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'

[[plugins]]
repo = 'junegunn/fzf.vim'
hook_add = '''
	command! -bang -nargs=? -complete=dir Files
	  \ call fzf#vim#files(<q-args>, fzf#vim#with_preview(), <bang>0)
	let g:fzf_layout = { 'down': '~40%' }
	nnoremap <silent> ,f :<C-u>Files<CR>
	nnoremap <silent> ,b :<C-u>Buffers<CR>
	nnoremap <silent> ,l :<C-u>BLines<CR>
	nnoremap <silent> ,h :<C-u>History<CR>
'''

[[plugins]] # 検索を改善
repo = 'haya14busa/incsearch.vim'
hook_add = '''
	let g:incsearch#auto_nohlsearch = 1
	map /  <Plug>(incsearch-forward)
	map ?  <Plug>(incsearch-backward)
	map g/ <Plug>(incsearch-stay)
'''

[[plugins]] # fuzzy検索
repo = 'haya14busa/incsearch-fuzzy.vim'
depends = ['incsearch.vim']
hook_add = '''
	map z/ <Plug>(incsearch-fuzzy-/)
	map z? <Plug>(incsearch-fuzzy-?)
	map zg/ <Plug>(incsearch-fuzzy-stay)
'''

[[plugins]] # migemo検索
repo = 'haya14busa/incsearch-migemo.vim'
depends = ['incsearch.vim']
hook_add = '''
	map s/ <Plug>(incsearch-migemo-/)
	map s? <Plug>(incsearch-migemo-?)
	map sg/ <Plug>(incsearch-migemo-stay)
'''

[[plugins]] # 日本語ヘルプ
repo = 'vim-jp/vimdoc-ja'

# ----MATLAB----
# [[plugins]] # matlab
# repo = 'daeyun/vim-matlab'
# on_ft = ['matlab']
# hook_add = '''
#     let g:matlab_server_launcher = 'vim'
# '''

