#!/usr/bin/env bash

trap 'echo Error: $0:$LINENO stopped; exit 1' ERR INT
set -euo pipefail

if [ -z "${DOTPATH:-}" ]; then
	DOTPATH=$HOME/dotfiles
	export DOTPATH
fi

# load useful functions
. "$DOTPATH"/etc/scripts/header.sh

echo ""
info "Start creating symbolic links."

ln -fs "${DOTPATH}/.clang-format" "${HOME}/.clang-format"
ln -fs "${DOTPATH}/.latexmkrc" "${HOME}/.latexmkrc"
ln -fs "${DOTPATH}/.tmux.conf" "${HOME}/.tmux.conf"
ln -fs "${DOTPATH}/.zshrc" "${HOME}/.zshrc"

mkdir -p "${HOME}/.config"

# TODO: ディレクトリが存在する場合は消してからリンク
ln -fs "${DOTPATH}/.config/efm-langserver" "${HOME}/.config/efm-langserver"
ln -fs "${DOTPATH}/.config/nvim" "${HOME}/.config/nvim"
ln -fs "${DOTPATH}/.config/alacritty" "${HOME}/.config/alacritty"
ln -fs "${DOTPATH}/.config/rofi" "${HOME}/.config/rofi"
ln -fs "${DOTPATH}/.config/git" "${HOME}/.config/git"
ln -fs "${DOTPATH}/.config/wezterm" "${HOME}/.config/wezterm"
ln -fs "${DOTPATH}/.config/zeno" "${HOME}/.config/zeno"

mkdir -p "${HOME}/.claude"
ln -fs "${DOTPATH}/.claude/commands" "${HOME}/.claude/commands"

# .config/hoge以下にファイルが自動で作成される場合、
# リンクはディレクトリではなくファイルのみにする
mkdir -p "${HOME}/.config/i3"
ln -fs "${DOTPATH}/.config/i3/config" "${HOME}/.config/i3/config"

mkdir -p "${HOME}/.config/lazygit"
ln -fs "${DOTPATH}/.config/lazygit/config.yml" "${HOME}/.config/lazygit/config.yml"

echo ""
