#!/usr/bin/env bash

trap 'echo Error: $0:$LINENO stopped; exit 1' ERR INT
set -euo pipefail

if [ -z "${DOTPATH:-}" ]; then
  DOTPATH=$HOME/dotfiles; export DOTPATH
fi

# load useful functions
. "$DOTPATH"/etc/scripts/header.sh

echo ""
info "Start creating symbolic links."

ln -fs ${DOTPATH}/.clang-format ${HOME}/.clang-format
ln -fs ${DOTPATH}/.dircolors ${HOME}/.dircolors
ln -fs ${DOTPATH}/.latexmkrc ${HOME}/.latexmkrc
ln -fs ${DOTPATH}/.tmux.conf ${HOME}/.tmux.conf
ln -fs ${DOTPATH}/.vimrc ${HOME}/vimrc.
ln -fs ${DOTPATH}/.zshrc ${HOME}/.zshrc
mkdir -p ${HOME}/.config
ln -fs ${DOTPATH}/.flake8 ${HOME}/.config/flake8
mkdir -p ${HOME}/.config/efm-langserver
ln -fs ${DOTPATH}/.config/efm-langserver/config.yaml ${HOME}/.config/efm-langserver/config.yaml

echo ""
