#!/usr/bin/env bash

trap 'echo Error: $0:$LINENO stopped; exit 1' ERR INT
set -euo pipefail

if [ -z "${DOTPATH:-}" ]; then
	DOTPATH=$HOME/dotfiles
	export DOTPATH
fi

# load useful functions
. "$DOTPATH"/etc/scripts/header.sh

echo ""
info "Start creating symbolic links."

ln -fs "${DOTPATH}/.clang-format" "${HOME}/.clang-format"
ln -fs "${DOTPATH}/.latexmkrc" "${HOME}/.latexmkrc"
ln -fs "${DOTPATH}/.tmux.conf" "${HOME}/.tmux.conf"
ln -fs "${DOTPATH}/.zshrc" "${HOME}/.zshrc"

mkdir -p "${HOME}/.config"

ln -fs "${DOTPATH}/.config/efm-langserver" "${HOME}/.config/efm-langserver"
ln -fs "${DOTPATH}/.config/nvim" "${HOME}/.config/nvim"
ln -fs "${DOTPATH}/.config/alacritty" "${HOME}/.config/alacritty"
ln -fs "${DOTPATH}/.config/rofi" "${HOME}/.config/rofi"

mkdir -p "${HOME}/.config/i3"
ln -fs "${DOTPATH}/.config/i3/config" "${HOME}/.config/i3/config"

mkdir -p "${HOME}/.config/wezterm"
ln -fs "${DOTPATH}/.config/wezterm/wezterm.lua" "${HOME}/.config/wezterm/wezterm.lua"

mkdir -p "${HOME}/.config/git"
ln -fs "${DOTPATH}/.config/git" "${HOME}/.config/git"

echo ""
