[[plugins]] # bかsbで近いペアをtextobj
repo = 'osyo-manga/vim-textobj-multiblock'
depends = 'vim-textobj-user'
on_map = [['xo', '<Plug>(textobj-multiblock-']]
hook_add = '''
    omap ab <Plug>(textobj-multiblock-a)
    omap ib <Plug>(textobj-multiblock-i)
    xmap ab <Plug>(textobj-multiblock-a)
    xmap ib <Plug>(textobj-multiblock-i)
'''

[[plugins]] # 引数や配列の入れ替え
repo = 'machakann/vim-swap'
on_map = [['nxo', '<Plug>(swap-']]
hook_add = '''
    omap i, <Plug>(swap-textobject-i)
    xmap i, <Plug>(swap-textobject-i)
    omap a, <Plug>(swap-textobject-a)
    xmap a, <Plug>(swap-textobject-a)
    nmap g< <Plug>(swap-prev)
    nmap g> <Plug>(swap-next)
    nmap gs <Plug>(swap-interactive)
'''
hook_source = '''
    let g:swap#rules = deepcopy(g:swap#default_rules)
    let g:swap#rules += [{
        \   'filetype': ['html', 'vue', 'md'],
        \   'delimiter': ['\s'],
        \   'surrounds': ['class="', '"', 0],
        \ },{
        \   'filetype': ['html', 'vue', 'md'],
        \   'delimiter': ['\s'],
        \   'surrounds': ["class='", "'", 0],
        \ }]
'''
