# プラグインの管理
[[plugins]] # これ使うのに必要
repo = 'Shougo/dein.vim'

[[plugins]] # ヤンク時に一瞬ハイライト
repo = "machakann/vim-highlightedyank"
hook_add = '''
let g:highlightedyank_highlight_duration = 300
'''

[[plugins]] # テキストオブジェクトの追加のため
repo = 'kana/vim-textobj-user'

[[plugins]] # 括弧などを入力したときの挙動をスマートに補完
repo = 'jiangmiao/auto-pairs'
hook_add = '''
let g:AutoPairsFlyMode = 1
autocmd vimrc Filetype tex let b:AutoPairs = deepcopy(g:AutoPairs)
autocmd vimrc Filetype tex let b:AutoPairs['$'] = '$'
'''

[[plugins]] # カラースキーム
repo = 'morhetz/gruvbox'
hook_add = '''
set background=dark
autocmd vimrc VimEnter * nested colorscheme gruvbox
'''

[[plugins]] # インデントの深さを可視化(要tabstop&shiftwidth設定)
repo = 'nathanaelkane/vim-indent-guides'
hook_add = '''
let g:indent_guides_enable_on_vim_startup = 1
let g:indent_guides_auto_colors = 0
let g:indent_guides_start_level = 2
hi IndentGuidesOdd  ctermbg=black
hi IndentGuidesEven ctermbg=darkgrey
'''

[[plugins]] # %を拡張
repo = 'andymass/vim-matchup'

[[plugins]] # 括弧関連便利になる
repo = 'machakann/vim-sandwich'

[[plugins]] # nvim系に必要
repo = 'roxma/nvim-yarp'
if = "!has('nvim')"

[[plugins]] # nvim系に必要
repo = 'roxma/vim-hug-neovim-rpc'
if = "!has('nvim')"

[[plugins]] # スニペット集
repo = 'honza/vim-snippets'

# スニペット定義ファイル
[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]] # ステータスラインとバッファ表示の強化
repo = 'vim-airline/vim-airline'
depends = ['vim-airline-themes']
hook_add = '''
" ステータスラインの表示内容強化
set laststatus=2 " ステータスラインを常に表示
set noshowmode   " 現在のモードを日本語表示しない
set showcmd      " 打ったコマンドをステータスラインの下に表示
set ruler        " ステータスラインの右側にカーソルの現在位置を表示する
let g:airline_theme = 'powerlineish'
let g:airline#extensions#branch#enabled = 1
let g:airline#extensions#tagbar#enabled = 1
let g:airline#extensions#wordcount#enabled = 0
if !has('nvim')
    let g:airline#extensions#tabline#enabled = 1
    let g:airline#extensions#tabline#formatter = 'unique_tail'
    let g:airline#extensions#tabline#alt_sep = 1
endif
let g:airline#extensions#default#layout = [
\ [ 'a', 'b', 'c' ],
\ [ 'x', 'y', 'z', 'warning' , 'error']]
let g:airline#extensions#default#section_truncate_width = {
\ 'b': 79,
\ 'x': 60,
\ 'y': 100,
\ 'z': 45,
\ 'warning': 80,
\ 'error': 80,
\ }
let g:airline_section_z = '%3v:%l/%L %3p%%'
'''

[[plugins]]
repo = 'romgrk/barbar.nvim'
if = "has('nvim')"
hook_add = '''
let g:bufferline = get(g:, 'bufferline', {})
let g:bufferline.icons = v:false
let g:bufferline.icon_separator_active = '|'
let g:bufferline.icon_separator_inactive = '|'
let g:bufferline.icon_close_tab = 'x'
let g:bufferline.icon_close_tab_modified = '●'
let g:bufferline.icon_pinned = 'L'
let g:bufferline.insert_at_end = v:true
nnoremap <Leader><Space> :BufferPick<CR>
'''
