# on_ftのやつを書く
[[plugins]] # TOMLのシンタックスハイライト
repo  = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]] # csvを見やすく
repo = 'mechatroner/rainbow_csv'
on_ft ="csv"
hook_add = '''
    let g:disable_rainbow_hover = 1
'''

# ----カーソル位置のコンテキストに合わせてファイルタイプを切り替え----
[[plugins]] # 判定ライブラリ
repo = 'Shougo/context_filetype.vim'
on_ft = ['vim','toml','markdown','md','mdwn','mkd','mkdn','mark','python','html']
hook_add = '''
    function! My_context_on()
        let g:context_filetype#filetypes = {
        \ 'python' :[
        \ {
            \ 'start' : '=\s.\?"\{3}$',
            \ 'end': '"\{3}$',
            \ 'filetype' : 'html',
        \ },
        \ ],
        \}
    endfunction
    call My_context_on()
    function! My_context_off()
        let g:context_filetype#filetypes = {
        \ 'python' :[
        \ {
            \ 'start' : 'template = "\{3}',
            \ 'end': '"\{3}',
            \ 'filetype' : 'html',
        \ },
        \ ],
        \}
    endfunction
'''

[[plugins]]
repo = 'osyo-manga/vim-precious'
on_ft = ['vim','toml','markdown','md','mdwn','mkd','mkdn','mark','python','html']
depends = ['context_filetype.vim']
hook_add = '''
    let g:precious_enable_switchers = {'defx': {'setfiletype': 0}}
'''

[[plugins]] # Emmet
repo = 'mattn/emmet-vim'
on_ft = ['html', 'css', 'php', 'xml', 'javascript']
hook_add = """
    let g:user_emmet_settings = {
    \ 'variables' : {
    \     'lang' : 'ja',
    \}}
"""

[[plugins]] # css, html, less, sass, scss, stylus, vim の色付け
repo = 'ap/vim-css-color'
on_ft = ['css']

# ----Markdownサポート----
[[plugins]] # Markdownの編集をサポート
repo = 'plasticboy/vim-markdown'
on_ft = ['markdown','md','mdwn','mkd','mkdn','mark']
hook_add = '''
    let g:vim_markdown_folding_disabled=1
    let g:vim_markdown_new_list_item_indent = 0
    let g:vim_markdown_frontmatter = 1
'''

[[plugins]] # テーブルの生成を補助?
repo = 'godlygeek/tabular'
on_ft = ['markdown','md','mdwn','mkd','mkdn','mark']

[[plugins]] # テーブルの生成
repo = 'dhruvasagar/vim-table-mode'
on_ft = ['markdown','md','mdwn','mkd','mkdn','mark']
hook_add = '''
    let g:table_mode_corner='|'
    let g:table_mode_tableize_map = '<Leader>tb'
'''
