[[plugins]] # スニペット管理
repo = 'Shougo/neosnippet.vim'
depends = ['neosnippet-snippets','context_filetype.vim']
on_event = 'InsertEnter'
on_ft = 'snippet'
hook_add = '''
    let g:neosnippet#snippets_directory = ['~/dotfiles/vim/mysnippet']
    let g:neosnippet#enable_completed_snippet = 1 " 関数スニペットを展開
    let g:neosnippet#expand_word_boundary = 0 " jump時に間違えて補完されないようにオフ
'''

[[plugins]] # 補完とLSP
repo = 'neoclide/coc.nvim'
build = './install.sh nightly'
depends = ['neosnippet.vim']
on_event = "VimEnter"
hook_add = '''
    set updatetime=300
    let g:coc_global_extensions = [
    \ 'coc-json',
    \ 'coc-highlight',
    \ 'coc-word',
    \ 'coc-snippets',
    \ 'coc-neosnippet',
    \ 'coc-css',
    \ 'coc-html',
    \ 'coc-tsserver',
    \ 'coc-emmet',
    \ 'coc-vimlsp',
    \ 'coc-vimtex',
    \ ]
    let g:airline#extensions#coc#error_symbol =  ""
    let g:airline#extensions#coc#warning_symbol = ""
    let g:airline_section_error = '%{airline#util#wrap(airline#extensions#coc#get_error(),0)}'
    let g:airline_section_warning = '%{airline#util#wrap(airline#extensions#coc#get_warning(),0)}'
    let g:coc_start_at_startup=1
    let g:coc_config_home = '~/dotfiles/vim'
'''
hook_source = '''
    highlight link CocHighlightText GruvboxBlueSign
    autocmd vimrc CursorHold * silent call CocActionAsync('highlight')
    autocmd User CocJumpPlaceholder call CocActionAsync('showSignatureHelp')
    autocmd CursorHoldI,CursorMovedI * silent! call CocAction('showSignatureHelp')
    nnoremap <F10> :<C-u>CocConfig<CR>
    inoremap <C-g> <C-o>:call CocActionAsync('showSignatureHelp')<CR>
    nmap <silent> [c <Plug>(coc-diagnostic-prev)
    nmap <silent> ]c <Plug>(coc-diagnostic-next)
    nmap <silent> gd <Plug>(coc-definition)
    nmap <silent> gD <Plug>(coc-type-definition)
    nmap <silent> gi <Plug>(coc-implementation)
    nmap <silent> gr <Plug>(coc-references)
    nmap <F2> <Plug>(coc-rename)
    nnoremap <silent> K :call <SID>show_documentation()<CR>
    function! s:show_documentation()
        if (index(['vim','help'], &filetype) >= 0)
            execute 'h '.expand('<cword>')
        else
            call CocAction('doHover')
        endif
    endfunction
    omap iF <Plug>(coc-funcobj-i)
    omap aF <Plug>(coc-funcobj-a)
    vmap iF <Plug>(coc-funcobj-i)
    vmap aF <Plug>(coc-funcobj-a)
    imap <silent><expr> <C-k>
    \ neosnippet#expandable_or_jumpable() ? "\<Plug>(neosnippet_expand_or_jump)" :
    \ coc#expandableOrJumpable() ? "\<C-r>=coc#rpc#request('doKeymap', ['snippets-expand-jump',''])\<CR>" :
    \ pumvisible() ? coc#_select_confirm() :
    \ coc#refresh()
    smap <silent><expr> <C-k>
    \ neosnippet#expandable_or_jumpable() ? "\<Plug>(neosnippet_expand_or_jump)" :
    \ coc#expandableOrJumpable() ? "\<C-r>=coc#rpc#request('doKeymap', ['snippets-expand-jump',''])\<CR>" :
    \ pumvisible() ? coc#_select_confirm() :
    \ coc#refresh()
    xmap <C-k> <Plug>(neosnippet_expand_target)
    let g:coc_snippet_next =  '<c-k>'
    let g:coc_snippet_prev = '<s-tab>'
'''

[[plugins]] # tagジャンプ
repo = 'majutsushi/tagbar'
on_cmd = 'TagbarToggle'
hook_add = '''
	let g:tagbar_width = 30
	let g:tagbar_sort = 0
	let g:tagbar_map_togglesort = 'S'
	nnoremap <silent> <leader>tt :TagbarToggle<CR>
	let g:tagbar_type_markdown = {
		\ 'ctagstype': 'markdown',
		\ 'ctagsbin' : $HOME . '/.vim/dein/repos/github.com/jszakmeister/markdown2ctags/markdown2ctags.py',
		\ 'ctagsargs' : '-f - --sort=yes',
		\ 'kinds' : [
		\ 's:sections',
		\ 'i:images'
		\ ],
		\ 'sro' : '|',
		\ 'kind2scope' : {
		\ 's' : 'section',
		\ },
		\ 'sort': 0,
		\ }
'''
