[theme]
theme = "bad-wolf"

[icons]
icons = "awesome6"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
[block.format]
full = "$icon $used/$total ($available free)"
short = "$icon $available free"

[[block]]
block = "memory"
interval = 60
warning_mem = 80
critical_mem = 95
[block.format]
full = " $icon $mem_used/$mem_total($mem_used_percents)"
short = "$mem_used_percents"

[[block]]
block = "battery"
interval = 10
[block.format]
full = " $icon $percentage $time "
short = "$percentage"

[[block]]
block = "music"
format = " $icon $volume_icon $combo $play $next| "
seek_step_secs = 10
[[block.click]]
button = "up"
action = "volume_up"
[[block.click]]
button = "down"
action = "volume_down"
[[block.click]]
button = "forward"
action = "seek_forward"
[[block.click]]
button = "back"
action = "seek_backward"

[[block]]
block = "sound"
step_width = 3

[[block]]
block = "backlight"

[[block]]
block = "time"
interval = 10
timezone = "Asia/Tokyo"
[block.format]
full = "$timestamp.datetime(f:'%m/%d %a %R', l:ja_JP)"
short = "$timestamp.datetime(f:'%R', l:ja_JP)"
