presets:
  dev:
    name: dev
    description: Editor/Server | AI/editprompt
    layout:
      type: horizontal
      ratio: [1, 1]
      panes:
        - type: vertical
          ratio: [1, "12c"]
          panes:
            - name: "other"
              command: >-
                tmux set-option -p -t {{this_pane}} @role other;
                git status -s | grep . || echo '変更なし'
            - name: "server"
              command: "tmux set-option -p -t {{this_pane}} @role server"
        - type: vertical
          ratio: [1, "10c"]
          panes:
            - name: "claude"
              command: >-
                tmux set-option -p -t {{this_pane}} @role claude;
                claude
            - name: "editprompt"
              command: >-
                tmux set-option -p -t {{this_pane}} @role editprompt;
                node ~/ghq/github.com/eetann/editprompt/dist/index.js open --editor nvim --target-pane {{pane_id:claude}} --always-copy
              ephemeral: true
              focus: true
  empty:
    name: empty
    description: プロセス終了用の単一ペイン
    command: ""
