presets:
  dev:
    name: dev
    description: Editor/Server | AI/editprompt
    layout:
      type: horizontal
      ratio: [1, 1]
      panes:
        - type: vertical
          ratio: [1, "12c"]
          panes:
            - name: "editor"
              command: "git status -c"
            - name: "terminal"
        - type: vertical
          ratio: [1, "10c"]
          panes:
            - name: "claude"
              command: "claude"
            - name: "editprompt"
              command: "node ~/ghq/github.com/eetann/editprompt/dist/index.js open --editor nvim --target-pane {{pane_id:claude}} --always-copy"
              ephemeral: true
              focus: true
  empty:
    name: empty
    description: プロセス終了用の単一ペイン
    command: ""
